config/routes.rb
Rails.application.routes.draw do
  root to: 'envelopes#new'

  resources :envelopes, only: [:new, :create, :show, :update] do
    resources :seals, only: [:create, :destroy]
    resource :session, only: [:new, :create, :destroy]
  end

  resources :seals, only: :show do
    post :opening
    get :contents
  end

end

app/models/envelope.rb
class Envelope < ActiveRecord::Base
  has_secure_password
  has_many :seals

  validates :owner_email, {
    presence: true,
    format: /.+@.+/
  }

  after_create :reload # so we've got our UUID

  def to_param
    uuid
  end

end

app/models/seal.rb
class Seal < ActiveRecord::Base
  scope :broken, -> { where(sealed: false) }

  belongs_to :envelope
  before_create :generate_token

  validates_presence_of :name

  after_create :reload # so we've got our UUID

  def envelope_name
    envelope.name
  end

  def notification_email
    envelope.owner_email
  end

  def formatted_token
    token.scan(/.{1,4}/).join(' ')
  end

  def to_param
    uuid
  end

  def contents
    envelope.contents
  end

  def build_opening(attrs={})
    SealOpening.new attrs.merge seal: self
  end

private

  def generate_token
    self.token ||= SecureRandom.hex(6)
  end

end

app/models/seal_opening.rb
class SealOpening
  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor :token, :seal

  validates_presence_of :token, :seal
  validate :valid_token

  def perform
    return unless valid?

    Seal.transaction do
      seal.update_attributes! sealed: false, opened_at: Time.now
      SealMailer.opening_email(seal).deliver_later
    end
  end

private

  def valid_token
    errors.add :token, :invalid unless normalized_token == seal.token # not timing safe fwiw
  end

  def normalized_token
    token.gsub /\s+/, ''
  end

end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :envelope_uuid, :password

  validates_presence_of :password

  def authorized_envelope
    return unless valid?

    envelope.authenticate(password).tap do |successful|
      errors.add :password, :incorrect if ! successful
    end
  end

private

  def envelope
    @envelope ||= Envelope.find_by! uuid: envelope_uuid
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder

  include EnvelopeAuthorization

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html
end

app/controllers/concerns/envelope_authorization.rb
module EnvelopeAuthorization
  extend ActiveSupport::Concern

  UnauthorizatedRequestError = Class.new StandardError

  included do
    rescue_from UnauthorizatedRequestError, with: :redirect_to_sign_in
  end

private

  def redirect_to_sign_in(e)
    redirect_to new_envelope_session_path(e.envelope_uuid)
  end

  def authorize_envelope(uuid)
    envelope = Envelope.find_by! uuid: uuid
    envelope_authorized?(envelope) or raise UnauthorizatedRequestError, envelope
    envelope
  end

  def grant_authorization(envelope)
    session[:envelope_uuid] = envelope.uuid if envelope
  end

  def revoke_authorization
    session[:envelope_uuid] = nil
  end

  def envelope_authorized?(envelope)
    session[:envelope_uuid] == envelope.uuid
  end

end

class EnvelopeAuthorization::UnauthorizatedRequestError < StandardError
  attr_accessor :envelope

  def initialize(envelope)
    @envelope = envelope
  end

  def envelope_uuid
    envelope.uuid
  end
end

app/controllers/envelopes_controller.rb
class EnvelopesController < ApplicationController

  def show
    @envelope = authorize_envelope params[:id]
  end

  def new
    @envelope = Envelope.new
  end

  def create
    @envelope = Envelope.new
    @envelope.update_attributes envelope_params and grant_authorization @envelope
    respond_with @envelope
  end

  def update
    @envelope = authorize_envelope params[:id]
    @envelope.update_attributes envelope_params
    respond_with @envelope, action: :show
  end

private

  def envelope_params
    params.require(:envelope).permit :name, :contents, :password, :owner_email
  end
end

app/controllers/seals_controller.rb
class SealsController < ApplicationController

  def show
    @seal = Seal.find_by! uuid: params[:id]
    @opening = @seal.build_opening
  end

  def create
    @seal = envelope.seals.create params.require(:seal).permit :name
    respond_with @seal, location: @seal.envelope
  end

  def destroy
    @seal = envelope.seals.find_by! uuid: params[:id]
    @seal.destroy
    respond_with @seal, location: @seal.envelope
  end

  def opening
    @seal = Seal.find_by! uuid: params[:seal_id]
    @opening = @seal.build_opening params[:seal_opening]
    @opening.perform

    # What do we do once they break the seal?
    # We could redirect them back to seals#show and
    # add logic to the view to test if a seal's been broken
    # if seal.opened? -> show contents
    # else show form?
    #
    # This seems risky, since the *fundamental* business logic of the applicatio
    # is reduced to templating logic. WAY easier to accidentally break this and
    # harder to test since the difference is between a view with the contents and
    # a view without the contents.
    # Any test that is expect a page NOT to have content is easy to accidentally mess up
      # i.e. pass while inadvertantly revealing the content
      # there's an infinite number of scenarios that will pass that test
      # and exactly one that will fail it
      # c.f. the solution below, where ONLY if the action 404s will the test pass
    #
    # Instead, we'll redirect them to a subresource (another action on this controller)
    # In this action, we can scope our seal lookup to only be broken seals
    # and we can have a completely different view/template for rendering the content
    # with no logic. This is also much easier to test, since the difference
    # is now between a 404 and a 200 with envelope contents.
    #
    # It's now very hard to accidentally reveal the content when a user views the seal
    # and even if the user visits the `contents` url without officially breaking the seal
    # they'll get a 404.
    #
    # The failure case is really explicit here.
    respond_with @opening, location: [@seal, :contents], action: :show
  end

  def contents
    @seal = Seal.broken.find_by! uuid: params[:seal_id]
  end

private

  def envelope
    @envelope ||= authorize_envelope params[:envelope_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = Session.new envelope_uuid: params[:envelope_id]
  end

  def create
    @session = Session.new params[:session]
    grant_authorization @session.authorized_envelope
    respond_with @session, location: envelope_path(@session.envelope_uuid)
  end

  def destroy
    revoke_authorization
    redirect_to envelope_path(params[:envelope_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_text(icon, title="")
    "<span class='glyphicon glyphicon-#{icon}'></span> #{title}".html_safe
  end
end

app/views/application/_flash.html.erb
<%= content_tag :div, class: [:alert, "alert-info"] do -%>
  <%= flash[:notice] %>
<%- end -%>

app/views/envelopes/_form.html.erb
<%= bootstrap_form_for envelope do |f| %>
  <%= f.alert_message t('fix_errors') %>
  <%= f.text_field :name %>
  <%= f.text_field :owner_email %>
  <%= f.password_field :password %>
  <%= f.text_area :contents, rows: 10 %>
  <%= f.submit class: 'btn btn-primary', disable_with: :saving %>
<% end %>

app/views/envelopes/new.html.erb
<h1 class="page-header"><%= t '.title' %></h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form', envelope: @envelope %>
  </div>
  <div class="col-md-6">
    Blah
  </div>
</div>

app/views/envelopes/show.html.erb
<h1 class="page-header">
  <%= icon_text 'envelope' %>
  <%= @envelope.name %>
  <%= link_to icon_text('eye-close', t('.lock')), [@envelope, :session], method: :delete, class: 'btn btn-default btn-xs' %>
</h1>

<%= render 'flash' if flash.any? %>
<div class="row">
  <div class="col-md-6">
    <%= render 'envelopes/form', envelope: @envelope %>
  </div>
  <div class="col-md-6">
    <% if @envelope.seals.present? %>
      <table class="table">
        <% @envelope.seals.each do |s| %>
          <tr>
            <td><%= link_to s.name, s %></td>
            <td><code><%= s.formatted_token %></code></td>
            <td><%= t s.sealed ? 'seal.sealed' : 'seal.broken' %></td>
            <td><%= text_field_tag '', seal_url(s), class: 'form-control input-sm' %></td>
            <td>
              <%= button_to t('delete'), [@envelope, s], method: :delete, class: 'btn btn-danger btn-xs' %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p><%= t '.no_seals' %></p>
    <% end %>

    <%= bootstrap_form_for [@envelope, @envelope.seals.build], layout: :inline do |f| %>
      <%= f.text_field :name, placeholder: true, hide_label: true %>
      <%= f.submit class: 'btn btn-primary', disable_with: :sealing %>
    <% end %>
  </div>
</div>

app/views/layouts/_head.html.erb
<title><%= t :page_title %></title>
<%= csrf_meta_tags %>
<%= javascript_include_tag :application %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<%= stylesheet_link_tag    'application', media: 'all' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
</head>
<body>
  <div class="container">
  <%= yield %>
  </div>
</body>
</html>

app/views/layouts/seals.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
</head>
<body class="seal-page">
  <div class="container">
    <div class="envelope panel">
    <%= yield %>
    </div>
  </div>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/seals/contents.html.erb
<h1>
  <%= icon_text 'envelope' %>
  <%= @seal.envelope_name %>
</h1>

<div class="alert alert-success" role="alert">
  <p>
    <%= icon_text 'ok' %>
    <%= t('.broken_html', seal_name: @seal.name, notification_email: @seal.notification_email) %>
  </p>
</div>


<pre>
  <%= @seal.contents %>
</pre>

app/views/seals/new.html.erb
<h1>
  <%= icon_text 'envelope' %>
  <%= @seal.envelope_name %>
</h1>

<%= bootstrap_form_for [@seal.envelope, @seal] do |f| %>
  <%= f.text_field :name, placeholder: true, hide_label: true %>
  <%= f.submit class: 'btn btn-primary', disable_with: :sealing %>
<% end %>

app/views/seals/show.html.erb
<h1>
  <%= icon_text 'envelope' %>
  <%= @seal.envelope_name %>
</h1>

<div class="alert alert-warning" role="alert">
  <p>
    <%= icon_text 'lock' %>
    <%= t('.prompt_html', seal_name: @seal.name, notification_email: @seal.notification_email) %>
  </p>
</div>

<%= bootstrap_form_for @opening, url: [@seal, :opening], method: :post, layout: :inline do |f| %>
  <%= f.text_field :token, placeholder: true, hide_label: true %>
  <%= f.submit class: 'btn btn-primary', disable_with: :opening %>
<% end %>